spring:
  application:
    name: Coffee

  datasource:
    username: root
    password: Yuan230708
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coffee
mybatis:
  mapper-locations: classpath:mybatis/*.xml