spring:
  application:
    name: Coffee

  datasource:
    username: root

    password:tzxzjyzzyljjyzxdfwq0707
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.115.230.54:3306/coffee
mybatis:
  mapper-locations: classpath:mybatis/*.xml

