spring:
  application:
    name: Coffee

  datasource:
    username: root
<<<<<<< Updated upstream
    password: #pwd
=======
    password:
>>>>>>> Stashed changes
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coffee